<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="DESKTOP-OJSF9Q6" failures="2" tests="2" name="Default test(failed)" time="0.414" errors="0" timestamp="2020-12-25T12:01:36 IST">
  <testcase classname="group.fail" name="tc3" time="0.054">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.fail(Assert.java:95)
at group.fail.tc3(fail.java:24)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- tc3 -->
  <testcase classname="group.fail" name="tc5" time="0.017">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.fail(Assert.java:95)
at group.fail.tc5(fail.java:37)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- tc5 -->
  <testcase classname="group.fail" name="tc4" time="0.0">
    <ignored/>
  </testcase> <!-- tc4 -->
  <testcase classname="group.fail" name="tc2" time="0.0">
    <ignored/>
  </testcase> <!-- tc2 -->
  <testcase classname="group.fail" name="tc1" time="0.0">
    <ignored/>
  </testcase> <!-- tc1 -->
</testsuite> <!-- Default test(failed) -->
