<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-OJSF9Q6" failures="2" tests="2" name="Default test(failed)(failed)(failed)(failed)" time="0.171" errors="0" timestamp="2020-12-08T13:18:39 IST">
  <testcase classname="Failedtestcase.sample" name="TC2" time="0.048">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.fail(Assert.java:95)
at Failedtestcase.sample.TC2(sample.java:18)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- TC2 -->
  <testcase classname="Failedtestcase.sample" name="TC3" time="0.005">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.fail(Assert.java:95)
at Failedtestcase.sample.TC3(sample.java:25)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- TC3 -->
  <testcase classname="Failedtestcase.sample" name="TC1" time="0.0">
    <ignored/>
  </testcase> <!-- TC1 -->
</testsuite> <!-- Default test(failed)(failed)(failed)(failed) -->
